CREATE TABLE IF NOT EXISTS Users
(
  userID BIGINT AUTO_INCREMENT NOT NULL,
  username VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  isEnabled boolean DEFAULT TRUE,
  PRIMARY KEY (userID)
);

CREATE TABLE IF NOT EXISTS UserProfile
(
    id BIGINT AUTO_INCREMENT NOT NULL,
    userID BIGINT NOT NULL,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    phoneNumber VARCHAR(20),
    address VARCHAR(255) NOT NULL,
    FOREIGN KEY (userID) REFERENCES Users (userID),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS UserRoles
(
    id BIGINT AUTO_INCREMENT NOT NULL,
    userID BIGINT NOT NULL,
    role ENUM ('ADMIN', 'USER'),
    FOREIGN KEY (userID) REFERENCES Users (userID),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS UserFinancialGoals
(
    id BIGINT AUTO_INCREMENT NOT NULL,
    userID BIGINT NOT NULL,
    goal_name VARCHAR(255) NOT NULL,
    targetAmount DECIMAL(10, 3) NOT NULL,
    currentAmount DECIMAL(10, 3) NOT NULL,
    due_date date NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (userID) REFERENCES Users (userID),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS UserAccounts
(
    id               BIGINT AUTO_INCREMENT NOT NULL,
    userID           BIGINT                NOT NULL,
    accountType      VARCHAR(50)           NOT NULL,
    institution_name VARCHAR(100)          NOT NULL,
    balance          DECIMAL(10, 3)        NOT NULL,
    createdAt        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES Users (userID),
    PRIMARY KEY (id)
);


